<<<<<<< HEAD
<<<<<<< HEAD

=======
/*
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
*/
>>>>>>> e7a11db (Initial commit of new website under development)
=======

>>>>>>> 9b63eb1 (Actually Added Documents)
// frontend/src/app/layout.js (was .tsx)
import { Inter } from 'next/font/google';
import './globals.css'; // Global styles
import Header from '../components/Header';
import Footer from '../components/Footer';
import SideMenu from '../components/SideMenu';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Demonstration Web Project',
    description: 'A Next.js and Express.js demonstration project',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="flex flex-col min-h-screen">
                    <Header />
                    <div className="flex flex-1">
                        <SideMenu />
                        <main className="flex-1 p-8">
                            {children}
                        </main>
                    </div>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
